### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by Wolf727** [Agentew04/RodrigoChain#1]
Is the mainnet already up and running? how to install blockchain if https://github.com/Agentew04/UniChain/blob/main is not available?

**Comment by Agentew04** [comment]
hello, it's not up yet. It still needs a P2P and a server to be created and set up. I'm currently developing the command line interface that will manage the connection in the future. You can read the README file [here](https://github.com/Agentew04/UniChain/blob/main/README.md)
